apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  annotations:
    # NOTE this allows the secret to be overwritten by SealedSecret
    sealedsecrets.bitnami.com/managed: "true"
