name: ArgoCD Dependabot
on:
  schedule:
    - cron: "0 10 * * *" # every day, 10 am UTC
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1.7.0

      - name: Get latest release
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        id: latest
        with:
          owner: argoproj
          repo: argo-cd
          excludes: prerelease,draft

      - name: Get current version
        id: current
        run: |
          echo "::set-output name=version::$(sed -n 's!.*/argo-cd/\(v[^/]*\)/.*!\1!p' source/kustomization.yaml | head -n1)"

      - name: Update version to latest
        run: |
          sed -i 's!\(/argo-cd/\)v[^/]*!\1${{ steps.latest.outputs.release }}!' source/kustomization.yaml

      - name: Render install.yaml
        run: |
          kustomize build source/ > install.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "fix(deps): bump argoproj/argo-cd from ${{ steps.current.outputs.version }} to ${{ steps.latest.outputs.release }}"
          commit-message: "fix(deps): bump argoproj/argo-cd from ${{ steps.current.outputs.version }} to ${{ steps.latest.outputs.release }}"
          body: |
            Bumps argoproj/argo-cd to latest version.
            
            https://github.com/argoproj/argo-cd/releases/tag/${{ steps.latest.outputs.release }}
          branch: dependabot/kustomize/argocd
          delete-branch: true
          labels: dependencies,kustomize
